import FeatureCard from "./FeatureCard";

export default function Features() {
  const features = [
    {
      title: "Jailbreak Detection",
      description:
        "Evaluate whether a model can be manipulated through adversarial prompts and prompt injections.",
    },
    {
      title: "Bias Analysis",
      description:
        "Measure unequal treatment and demographic bias across multiple protected groups.",
    },
    {
      title: "Toxicity Scoring",
      description:
        "Detect harmful, offensive, or unsafe responses using automated classifiers.",
    },
    {
      title: "Hallucination Testing",
      description:
        "Identify factual inaccuracies and unsupported claims generated by language models.",
    },
  ];

  return (
    <section className="mx-auto max-w-7xl px-6 py-24">
      <div className="mb-12 text-center">
        <h2 className="mb-4 text-4xl font-bold">
          Core Capabilities
        </h2>

        <p className="text-zinc-400">
          Everything needed to evaluate AI safety at scale.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {features.map((feature) => (
          <FeatureCard
            key={feature.title}
            title={feature.title}
            description={feature.description}
          />
        ))}
      </div>
    </section>
  );
}